[versions]
inventoryFramework = "3.7.1"
guava = "33.5.0-jre"
jetbrainsAnnotations = "26.0.2-1"
configurate = "4.2.0-GeyserMC-SNAPSHOT"
classgraph = "4.8.184"
adventure = "4.26.1"
commonsText = "1.15.0"
slf4j = "2.1.0-alpha1"
mongodb = "5.6.2"
hikari = "7.0.2"
lamp = "4.0.0-rc.14"
logback = "1.5.23"
junit = "6.0.1"
zapper = "1.0.3"
cytosis = "1.0-SNAPSHOT"
bstats = "3.1.0"
javapoet = "0.9.0"
gson = "2.13.2"
jsoup = "1.21.2"
clikt = "5.0.3"
kotlin-logging = "7.0.13"
autoService = "1.1.1"

[libraries]
inventoryFramework-api = { module = "me.devnatan:inventory-framework-api", version.ref = "inventoryFramework" }
inventoryFramework-platform = { module = "me.devnatan:inventory-framework-platform", version.ref = "inventoryFramework" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
configurate-gson = { module = "org.spongepowered:configurate-gson", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
commonsText = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
mongodb = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-bukkit = { module = "io.github.revxrsal:lamp.bukkit", version.ref = "lamp" }
lamp-minestom = { module = "io.github.revxrsal:lamp.minestom", version.ref = "lamp" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
zapper = { module = "io.github.revxrsal:zapper.api", version.ref = "zapper" }
cytosis = { module = "net.cytonic:Cytosis", version.ref = "cytosis" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
javapoet = { module = "com.palantir.javapoet:javapoet", version.ref = "javapoet" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }